In [5]:
import numpy as np

In [6]:
x=np.array([1,2,3,4,5])

In [7]:
type(x)

numpy.ndarray

In [7]:
N=5
matrix = np.column_stack([x**(N-i-1) for i in range(N)]) 
print(matrix) 

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [38]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 

In [52]:
a1=np.array(a)
a1

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [101]:
asum = np.cumsum(a)
print(asum)

[  3   8  15  17  25  35  46 111 183 264 363 463 613]


In [105]:
def moving_average(asum):
    n=3
    asum[n:] = asum[n:] - asum[:-n] 
    return asum[n - 1:] / n

In [106]:
moving_average(asum).round()

array([  5.,   3.,   0.,  -3.,   1.,  20.,  41.,  58.,  32.,   1., -19.])